### ISSUE TITLE
Bluetooth receiver

### ISSUE THREAD

**Issue by jordancde** [jordandearsley/ZenSense#14]
Doesn't matter what language or library, needs to receive a string from the sensor via bluetooth and append it to a csv. Needs to be capable of running via a bash command (ex "python recievebt.py", "./recievebt.sh")

**Comment by IsidorEhrlich** [comment]
I'll try to get JAVA BLE working this afternoon.

**Comment by IsidorEhrlich** [comment]
I have been looking for APIs or Libraries that I could use but I have yet to find anything. If this fails I will try to make a Python script that writes it to a file. Also, the board uses Bluetooth Low Energy so many old Bluetooth libraries are not compatible.

**Comment by IsidorEhrlich** [comment]
I cannot find anything for both JAVA and Python, investigating serial transfer as an alternative. This will allow for us to use an additional Bluetooth module or simply use the wired cable connection.

**Comment by IsidorEhrlich** [comment]
I have found plenty of software that can easily read serial data. I can use this software to read serial data from the Arduino and save it to a file. This can be done by either getting a normal serial Bluetooth adapter and connecting it to the software or by simply plugging in the Arduino via USB.
